
language: python
python:
  - "3.6.1"
 
os: "ubuntu"
# whitelist

 
# Use this to prepare the system to install prerequisites or dependencies


# command to install dependencies
install: 
- "pip install -r requirements.txt"
- "pip install tushare"
# command to build
script: "python setup.py install"
 
#after_success:
    #"python easy_start_tushare.py"
